_platform_map = {
    "blair": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86803DA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86801JA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86802CA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86802AA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86803AA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86801EA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86801GA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
    "P86801AA1": {
        "dtb_list": [
            {"name": "blair.dtb"},
            #{"name": "holi.dtb"},
            #{
            #    "name": "blairp.dtb",
            #    "apq": True,
            #},
        ],
        "dtbo_list": [],
        "NOTE: excluded dtbo_list" : [
            #{"name": "blair-mtp-overlay.dtbo"},
            #{"name": "blair-qrd-overlay.dtbo"},
            #{"name": "blair-cdp-overlay.dtbo"},
            #{"name": "blair-atp-overlay.dtbo"},
            #{"name": "blair-mtp-usbc-overlay.dtbo"},
            #{"name": "blair-mtp-nopmi-overlay.dtbo"},
            {"name": "P86801AA1-qrd-nopmi-overlay.dtbo"},
            #{"name": "blairp-mtp-overlay.dtbo"},
            #{"name": "blairp-qrd-overlay.dtbo"},
            #{"name": "blairp-cdp-overlay.dtbo"},
            #{"name": "blairp-atp-overlay.dtbo"},
            #{"name": "blairp-mtp-usbc-overlay.dtbo"},
            #{"name": "blairp-mtp-nopmi-overlay.dtbo"},
            #{"name": "blairp-qrd-nopmi-overlay.dtbo"},
            #{"name": "holi-mtp-overlay.dtbo"},
            #{"name": "holi-qrd-overlay.dtbo"},
            #{"name": "holi-cdp-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-overlay.dtbo"},
            #{"name": "holi-atp-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-usbc-pm6125-overlay.dtbo"},
            #{"name": "holi-mtp-pm6125-nopmi-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-overlay.dtbo"},
            #{"name": "holi-cdp-lcd-pm6125-overlay.dtbo"},
            #{"name": "holi-qrd-pm6125-nopmi-overlay.dtbo"},
        ],
    },
}

def _get_dtb_lists(target, dt_overlay_supported):
    if not target in _platform_map:
        fail("{} not in device tree platform map!".format(target))

    ret = {
        "dtb_list": [],
        "dtbo_list": [],
    }

    for dtb_node in [target] + _platform_map[target].get("binary_compatible_with", []):
        ret["dtb_list"].extend(_platform_map[dtb_node].get("dtb_list", []))
        if dt_overlay_supported:
            ret["dtbo_list"].extend(_platform_map[dtb_node].get("dtbo_list", []))
        else:
            # Translate the dtbo list into dtbs we can append to main dtb_list
            for dtb in _platform_map[dtb_node].get("dtb_list", []):
                dtb_base = dtb["name"].replace(".dtb", "")
                for dtbo in _platform_map[dtb_node].get("dtbo_list", []):
                    if not dtbo.get("apq", True) and dtb.get("apq", False):
                        continue

                    dtbo_base = dtbo["name"].replace(".dtbo", "")
                    ret["dtb_list"].append({"name": "{}-{}.dtb".format(dtb_base, dtbo_base)})

    return ret

def get_dtb_list(target, dt_overlay_supported = True):
    return [dtb["name"] for dtb in _get_dtb_lists(target, dt_overlay_supported).get("dtb_list", [])]

def get_dtbo_list(target, dt_overlay_supported = True):
    return [dtb["name"] for dtb in _get_dtb_lists(target, dt_overlay_supported).get("dtbo_list", [])]
